# **Description:**
# TO FILL
FROM quay.io/rh-aiservices-bu/instructlab-workbench-code-server-cuda:0.21.0

USER root

ARG HUGGINGFACE_API

#RUN ilab model download --rp mistralai/Mistral-7B-Instruct-v0.2 --hf-token $HUGGINGFACE_API
#RUN ilab model download --rp instructlab/granite-7b-lab --hf-token $HUGGINGFACE_API
RUN dnf install go -y

# Build golang
COPY web/ .

RUN go get
RUN go build

#! Entrypoint
ENTRYPOINT ["./main"]