#**Description:**
#
# Index page of k8s.land
#
# **Running:**
#
# ```sh
# podman run -d \
#   -p 8080:8080 \
#   --name index \
#   cdrage/index
# ```

FROM debian:sid

#! Install dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 &&\
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#! Files
COPY main.sh /
RUN mkdir /www
EXPOSE 8080
WORKDIR /www
COPY index.html /www/index.html

#! Entrypoint
ENTRYPOINT ["/main.sh"]
