# **Description:**
# > IMPORTANT NOTE: This is BOOTC. This is meant for bootable container applications. See: https://github.com/containers/podman-desktop-extension-bootc
#
# This Containerfile creates a k3s NODE on AMD64 using CentOS Stream 9. So you can run a k8s server on boot.
#
# You must know the IP address of the master in order for these nodes to connect.
#
# Notes:
# * The default user is root, and the ssh key is placed in /usr/ssh/root.keys this is enabled so we can scp / ssh and get the kubeconfig file (/etc/rancher/k3s/k3s.yaml)
# * a unique hostname must be set or else it is rejected by the master k3s server for being not unique
#
# Arguments are required in order to build this image with both your k3s token and your SSH public key. To do this, you must have the following (you can pass in this via --build-arg foo=bar on the CLI):
# * hostname=k8snode
# * server=https://IPADDRESS:6443
# * token=MySuperSecretK3sToken
# * sshpubkey=MySSHPublicKeyNOTThePrivateKey
#
# **Running:**
# 1. Create disk image using the above extension
# 2. Boot OS
# 3. See that it creates the k3s agent on boot / connects to the k8s server
# 4. use kubectl get nodes and you should see your server.

FROM quay.io/centos-bootc/centos-bootc:stream9

#! ARGUMENTS
#! Intentionally left blank so users know to pass them in... the build will fail if they don't.
ARG hostname
ARG server
ARG token
ARG sshpubkey

#! Install selinux requirements for k3s
RUN dnf install -y selinux-policy-base
RUN dnf install -y https://rpmfind.net/linux/centos-stream/9-stream/AppStream/aarch64/os/Packages/container-selinux-2.228.0-1.el9.noarch.rpm
RUN dnf install -y https://github.com/k3s-io/k3s-selinux/releases/download/v1.5.stable.1/k3s-selinux-1.5-1.el9.noarch.rpm

#! Set hostname
RUN echo ${hostname} > /etc/hostname

#! INSTALL AMD64 K3S
RUN curl -Lo /usr/local/bin/k3s https://github.com/k3s-io/k3s/releases/download/v1.29.4%2Bk3s1/k3s; chmod a+x /usr/local/bin/k3s
RUN echo "K3S_TOKEN=${token}" > /etc/systemd/system/k3s.service.env
RUN echo "K3S_URL=${server}" >> /etc/systemd/system/k3s.service.env
COPY usr/ /usr/
RUN systemctl enable k3s.service

#! Add the SSH key from sshpubkey so we can actually get the kubeconfig file
RUN set -eu; mkdir -p /usr/ssh && \
  echo 'AuthorizedKeysFile /usr/ssh/%u.keys .ssh/authorized_keys .ssh/authorized_keys2' >> /etc/ssh/sshd_config.d/30-auth-system.conf && \
  echo ${sshpubkey} > /usr/ssh/root.keys && chmod 0600 /usr/ssh/root.keys