# **Description:**
#
# Do not EVER run this in production. You have been warned.
#
# Here be dragons
# IMPORTANT NOTE: This is BOOTC. This is meant for bootable container applications.
#
# You do not run this as a normal container. Must use a tool such as: 
# https://github.com/osbuild/bootc-image-builder 
#
# In order to make a bootable OS that runs the server on boot.
#
# **Running:**
# 1. Boot OS
# 2. Login as root

FROM quay.io/fedora/fedora-bootc:40

#! Set password to root:root for testing purposes
RUN echo "root:root" | chpasswd
