# **Description:**
#
# Does nothing. Just compiles the linux kernel.
#
# Used for benchmarking running `podman build`.
#
# **Running:**
#
# N/A. Just `podman build` it.

FROM debian:buster
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    build-essential \
    fakeroot \
    libncurses-dev \
    bison \
    flex \
    libssl-dev \
    libelf-dev \
    bc \
    wget \
    cpio \
    rsync \
    && rm -rf /var/lib/apt/lists/*
ARG KERNEL_VERSION=5.10.1
RUN wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-${KERNEL_VERSION}.tar.xz \
    && tar -xvf linux-${KERNEL_VERSION}.tar.xz && rm linux-${KERNEL_VERSION}.tar.xz
WORKDIR /linux-${KERNEL_VERSION}
RUN make defconfig \
    && sed -i 's/CONFIG_DEBUG_KERNEL=y/CONFIG_DEBUG_KERNEL=n/' .config \
    && sed -i 's/# CONFIG_DEBUG_INFO is not set/CONFIG_DEBUG_INFO=n/' .config
RUN make -j$(nproc)
CMD ["bash"]
