#!/bin/bash

if [[ -z "$VCS_REF" ]]; then
    VCS_REF=$(git rev-parse --short HEAD)
fi

BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

docker build -t "$IMAGE_NAME" --build-arg VCS_REF="$VCS_REF" --build-arg BUILD_DATE="$BUILD_DATE" .

