variables:
    PUBLIC_TAG: 'strm/helloworld-http'
stages:
    - build

build:
    stage: build
    script:
        - export IMAGE_TAG=$(echo -en $CI_BUILD_REF_NAME | tr -c '[:alnum:]_.-' '-' | sed 's/master/latest/g')
        - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
        - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
        - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
        - docker tag "$CI_REGISTRY_IMAGE:$IMAGE_TAG" "$PUBLIC_TAG"
    tags:
        - docker
