# **Description:**
#
# Super simple helloworld container that says the hostname of the container
#
# **Running:**
#
# ```sh
# podman run -d \
#   -p 8080:8080 \
#   --name helloworld \
#   ghcr.io/cdrage/hello
# ```

FROM debian:sid

#! Install dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 &&\
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#! Files
COPY main.sh /
RUN mkdir /www
EXPOSE 8080
WORKDIR /www

#! Entrypoint
ENTRYPOINT ["/main.sh"]
