# **Description:**
#
# Very simple "steam server" container checker.
# 
# Checks to see if there is a game server running on port 27015 LOCALLY (same IP as actual server)
# meant to be ran alongside the steam server container.
# 
# **Running:**
#
# ```sh
# podman run -d \
#    --name gameserver \
#    -p 3000:3000
#    ghcr.io/cdrage/gameserver
# ```

#! Build Stage
FROM node:16-alpine
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build

#! Run Stage
FROM node:16-alpine
WORKDIR /app
COPY --from=0 /app/package*.json ./
RUN npm ci --production --ignore-scripts
COPY --from=0 /app/build ./

EXPOSE 3000
CMD ["node", "./index.js"]
