

# DISABLE SECURE BOOT PLEASE OMG

# built with:
# podman build --platform linux/amd64 -t git.k8s.land/cdrage/nvidia-test-base3 --security-opt label=disable --cap-add SYS_ADMIN .

# SEE OTHER FILE, must do certain nvidia-drivers stuff before hand.




# In practice you will need a base image with
# a compatible kernel+driver
FROM quay.io/fedora/fedora-bootc:40
# Add our configuration
#COPY etc/ /etc/

# Install other driver
RUN dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# TEST!
RUN dnf install -y akmod-nvidia
# THIS WORKS THOUGH:
# RUN dnf install -y akmod-nvidia
# and then bootc usroverlay and then akmods --force then modprobe nvidia and you get it..
RUN dnf install -y xorg-x11-drv-nvidia-cuda

# Install container toolkit
RUN curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | \
  sudo tee /etc/yum.repos.d/nvidia-container-toolkit.repo
RUN dnf install -y nvidia-container-toolkit

RUN echo "blacklist nouveau" > /etc/modprobe.d/blacklist_nouveau.conf

#RUN dracut --regenerate-all --force

# Maybe have to rebuild initram? i dunno
#RUN ls -lah /usr/lib/modules
#RUN set -x; kver=$(cd /usr/lib/modules && echo *); dracut -vf /usr/lib/modules/$kver/initramfs.img $kver

#RUN dnf -y module install nvidia-driver && \
  #    dnf install -y nvidia-container-toolkit && \
  #  rm /var/log/*.log /var/lib/dnf -rf
  #