# **Description:**
# > IMPORTANT NOTE: This is BOOTC. This is meant for bootable container applications. See: https://github.com/containers/podman-desktop-extension-bootc
#
# This is a "base" container that installs the nvidia drivers and the nvidia container toolkit. 
# This is meant to be used as a base for other containers that need GPU access.
#
# DISABLE SECURE BOOT! You have been warned! Disable boot is **KNOWN** to cause issues with the nvidia drivers.
# ENABLE 4G DECODING in the BIOS. This is needed for certain nvidia cards to work such as the Tesla P40.
#
# IMPORTANT NOTE:
# On boot, this will **not** have the nvidia drivers loaded it they are compiled. This is because akmods are suppose to be built on boot, but this doesn't work with bootc.
# Instead, the nvidia drivers will recompile + use akmod + modprobe on boot.. and may take a minute to load.
# If you have any systemd services that require the nvidia drivers, you will need to add a `After=nvidia-drivers.service` to the service or have it LATE in the boot order (ex. multi-user.target)
# to ensure that the nvidia drivers are loaded before the service starts.
#
# For example, if you have a podman container with --restart=always, you will need to add a `After=nvidia-drivers.service` to the podman-restart.service and podman-restart.timer. file.
# This has been done for you already within the nvidia-drivers.service and nvidia-toolkit-firstboot.service files.
#
# Note about nvidia-toolkit-fristboot.service file: This is a one-time service on boot that will create the /etc/cdi/nvidia.yaml file. This is necessary for podman
# to use gpu devices.
# 
#
# **Running:**
# 1. In your OTHER Containerfile, change `FROM quay.io/fedora/fedora-bootc:40` to `FROM git.k8s.land/cdrage/bootc-nvidia-base-fedora` / this Containerfile.
# 2. The nvidia drivers will recompile + use akmod + modprobe on boot.
# 3. Use nvidia-smi command within the booted container image to see if it works.
FROM quay.io/fedora/fedora-bootc:40

#! before ANYTHING, we update to the latest kernel..
#! this is to prevent any "missing kernel modules" on boot from happening.
RUN dnf update -y && dnf upgrade -y kernel kernel-modules

#! install from rpmfusion
RUN dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

#! akmod's are "suppose" to be built on boot, but this doesn't work with bootc.
RUN dnf install -y akmod-nvidia
RUN dnf install -y xorg-x11-drv-nvidia-cuda

#! install container toolkit
RUN curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | \
  sudo tee /etc/yum.repos.d/nvidia-container-toolkit.repo
RUN dnf install -y nvidia-container-toolkit

#! blacklist nouveau driver so nvidia can work
RUN echo "blacklist nouveau" > /etc/modprobe.d/blacklist_nouveau.conf

#! copy over all usr files
COPY usr/ /usr/

#! enable all the services
RUN systemctl enable nvidia-toolkit-firstboot.service
RUN systemctl enable nvidia-drivers.service