# **Description:**
#
# Used to generate aviation checklists. Based on the work by https://github.com/freerobby/aviation-checklist
# with the patch https://github.com/freerobby/aviation-checklist/pull/2
#
# **Running:**
#
# ```sh
# podman run -d \
#   -p 8080:80 \
#   --name aviation-checklist \
#   ghcr.io/cdrage/aviation-checklist
# ```

#! First stage: Build
FROM node:20.13.0 as build-stage
RUN apt-get update && apt-get install -y git
WORKDIR /app
RUN git clone https://github.com/cdrage/aviation-checklist .
RUN yarn install
RUN yarn build

#! Second stage: Setup the nginx server
FROM nginx:stable-alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
